[project]
name = "bili-vedio-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.3.0",
    "qrcode>=8.2",
    "requests>=2.32.4",
    "tqdm>=4.67.1",
]
